import { z } from "zod";

export const Declaration_Type = z.enum([
    'Form',
    'Activity',
    'AddressProof',
    'Autonomo',
    'Card',
    'ChildPension',
    'ChildSupport',
    'ContributionStatement',
    'Data',
    'Empresario',
    'InactiveCompany',
    'IncomeTaxExemption',
    'MEI',
    'NoAddressProof',
    'Penseion',
    'Pension',
    'Rent',
    'RentDetails',
    'RentIncome',
    'RentedHouse',
    'RuralWorker',
    'SingleStatus',
    'StableUnion',
    'Status',
    'WorkCard',
  ]);