import { z } from "zod"

export const ENTITY_SUBTYPE_DOC_ZOD = z.enum([

    `INSTITUTION_NAME`,
    `CNPJ`,
    `ANNOUNCEMENT`,
    `DISCLOSURE_PROOF`,
    `FINAL_RESULT`,
    `CEBAS_CERTIFICATE`,
    `SOCIAL_ASSISTANT_OPINION`,
    `CEBAS_EXTENSION`,
    `CEBAS_EDUCATION`,
    `CEBAS_NOTES_COPY`,
    'INFORMATION_REQUEST_CERTIFICATE',
    'INFORMATION_REQUEST_ANSWER'
])

export type ENTITY_SUBTYPE_DOC = z.infer<typeof ENTITY_SUBTYPE_DOC_ZOD>