import { AllEducationType } from "@prisma/client";
import { prisma } from "./lib/prisma";

// Função para normalizar o nome do curso
function normalizeName(name: string) {
    return name
        .normalize('NFD') // Normaliza para decompor caracteres acentuados
        .replace(/[\u0300-\u036f]/g, '') // Remove os acentos
        .toLowerCase() // Converte para minúsculas
        .replace(/\s+/g, ''); // Remove espaços
}

async function addCourses() {
    try {
        // Conjunto de dados a serem adicionados

        const courseHigh = {
            UndergraduateBachelor: [
                "Administração",
                "Administração Pública",
                "Agroecologia",
                "Agronegócio",
                "Agronomia",
                "Análise de Sistemas",
                "Antropologia",
                "Arquitetura e Urbanismo",
                "Arquivologia",
                "Artes",
                "Artes Cênicas",
                "Astronomia",
                "Biblioteconomia",
                "Biologia",
                "Biomedicina",
                "Bioquímica",
                "Canto",
                "Cenografia",
                "Ciência da Computação",
                "Ciências Biológicas",
                "Ciências Contábeis",
                "Ciências Econômicas",
                "Ciências Sociais",
                "Cinema e Audiovisual",
                "Composição e Regência",
                "Computação",
                "Comunicação e Marketing",
                "Comunicação Social",
                "Desenho Industrial",
                "Design",
                "Design de Ambientes",
                "Design de Games",
                "Design de Interiores",
                "Design de Moda",
                "Design de Produto",
                "Design Digital",
                "Design Gráfico",
                "Direção",
                "Direito",
                "Educação Física",
                "Enfermagem",
                "Engenharia Acústica",
                "Engenharia Aeroespacial",
                "Engenharia Aeronáutica",
                "Engenharia Agrícola",
                "Engenharia Agroindustrial",
                "Engenharia Agronômica",
                "Engenharia Ambiental",
                "Engenharia Automotiva",
                "Engenharia Bioenergética",
                "Engenharia Biomédica",
                "Engenharia Bioquímica",
                "Engenharia Biotecnológica",
                "Engenharia Cartográfica",
                "Engenharia Civil",
                "Engenharia da Computação",
                "Engenharia da Mobilidade",
                "Engenharia de Agrimensura",
                "Engenharia de Agronegócios",
                "Engenharia de Alimentos",
                "Engenharia de Aquicultura",
                "Engenharia de Automação",
                "Engenharia de Bioprocessos",
                "Engenharia de Biossistemas",
                "Engenharia de Biotecnologia",
                "Engenharia de Energia",
                "Engenharia de Gestão",
                "Engenharia de Informação",
                "Engenharia de Instrumentação, Automação e Robótica",
                "Engenharia de Manufatura",
                "Engenharia de Materiais",
                "Engenharia de Minas",
                "Engenharia de Pesca",
                "Engenharia de Petróleo",
                "Engenharia de Produção",
                "Engenharia de Recursos Hídricos",
                "Engenharia de Saúde e Segurança",
                "Engenharia de Sistemas",
                "Engenharia de Software",
                "Engenharia de Telecomunicações",
                "Engenharia de Transporte e Logística",
                "Engenharia Elétrica",
                "Engenharia Eletrônica",
                "Engenharia em Sistemas Digitais",
                "Engenharia Ferroviária e Metroviária",
                "Engenharia Física",
                "Engenharia Florestal",
                "Engenharia Geológica",
                "Engenharia Hídrica",
                "Engenharia Industrial",
                "Engenharia Mecânica",
                "Engenharia Mecatrônica",
                "Engenharia Metalúrgica",
                "Engenharia Naval",
                "Engenharia Química",
                "Engenharia Têxtil",
                "Estatística",
                "Farmácia",
                "Filosofia",
                "Física",
                "Fisioterapia",
                "Fonoaudiologia",
                "Geografia",
                "Gestão Ambiental",
                "Gestão da Informação",
                "Gestão de Políticas Públicas",
                "Gestão de Serviços de Saúde",
                "Gestão do Agronegócio",
                "Gestão Pública",
                "História",
                "Hotelaria",
                "Jornalismo",
                "Letras",
                "Marketing",
                "Matemática",
                "Mecânica Industrial",
                "Medicina",
                "Medicina Veterinária",
                "Moda",
                "Música",
                "Nutrição",
                "Odontologia",
                "Pedagogia",
                "Políticas Públicas",
                "Propaganda e Marketing",
                "Psicologia",
                "Publicidade e Propaganda",
                "Química",
                "Rádio, TV e Internet",
                "Relações Internacionais",
                "Relações Públicas",
                "Secretariado Executivo",
                "Serviço Social",
                "Sistemas de Informação",
                "Tecnologias Digitais",
                "Teologia",
                "Terapia Ocupacional",
                "Tradutor e Intérprete",
                "Turismo",
                "Zootecnia"
            ],
            UndergraduateLicense: [
                "Artes",
                "Artes Cênicas",
                "Artes Plásticas",
                "Artes Visuais",
                "Biologia",
                "Ciência da Computação",
                "Ciências Agrícolas",
                "Ciências da Natureza",
                "Ciências Exatas",
                "Ciências Sociais",
                "Computação",
                "Desenho e Plástica",
                "Educação do Campo",
                "Educação Especial",
                "Educação Física",
                "Enfermagem",
                "Filosofia",
                "Física",
                "Geografia",
                "História",
                "Informática",
                "Letras",
                "Matemática",
                "Música",
                "Pedagogia",
                "Programa Especial de Formação Pedagógica",
                "Psicologia",
                "Química",
                "Segunda licenciatura",
                "Teatro"
            ],
            UndergraduateTechnologist: [
                "Acupuntura",
                "Agrimensura",
                "Agrocomputação",
                "Agroecologia",
                "Agroindústria",
                "Agronegócio",
                "Agropecuária",
                "Alimentos",
                "Análise de Dados",
                "Análise e Desenvolvimento de Sistemas",
                "Apicultura e Meliponicultura",
                "Aquicultura",
                "Arqueologia",
                "Arquitetura de Dados",
                "Artes do Espetáculo",
                "Artes e Mídias Digitais",
                "Assessoria Executiva Digital",
                "Atividades de Inteligência e Gestão de Sigilos",
                "Auditoria em Saúde",
                "Automação de Escritórios e Secretariado",
                "Automação e Manufatura Digital",
                "Automação Industrial",
                "Banco de Dados",
                "Big Data e Inteligência Analítica",
                "Big Data no Agronegócio",
                "Biocombustíveis",
                "Bioenergia",
                "Bioinformática",
                "Biotecnologia",
                "Blockchain e Criptografia Digital",
                "Cafeicultura",
                "Cibersegurança",
                "Ciência de Dados",
                "Cinema e Audiovisual",
                "Coach Digital",
                "Coaching e Mentoring",
                "Coding",
                "Comércio Exterior",
                "Desenvolvimento para Web",
                "Design",
                "Design Comercial",
                "Design de Animação",
                "Design de Aplicações e Interfaces Digitais",
                "Design de Experiência e de Serviços",
                "Design de Games",
                "Design de Interiores",
                "Design de Moda",
                "Design de Produto",
                "Design Editorial",
                "Design Educacional",
                "Design Gráfico",
                "Devops",
                "Digital Influencer",
                "Digital Security",
                "E-Commerce",
                "Educação e Processos de Trabalho: Alimentação Escolar",
                "Educador Social",
                "Eletrônica Automotiva",
                "Eletrônica Industrial",
                "Eletrotécnica Industrial",
                "Embelezamento e Imagem Pessoal",
                "Empreendedorismo",
                "Energias Renováveis",
                "Escrita Criativa",
                "Estética e Cosmética",
                "Estilismo",
                "Estradas",
                "Eventos",
                "Fabricação Mecânica",
                "Filmmaker",
                "Finanças, Blockchain e Criptomoedas",
                "Gestão de Micro e Pequenas Empresas",
                "Gestão de Negócios",
                "Gestão de Pessoas",
                "Gestão de Produção Industrial",
                "Gestão de Qualidade na Saúde",
                "Gestão de Recursos Hídricos",
                "Gestão de Recursos Humanos",
                "Gestão de Representação Comercial",
                "Gestão de Resíduos de Serviços de Saúde",
                "Gestão de Saúde Pública",
                "Gestão de Segurança Privada",
                "Gestão de Seguros",
                "Gestão de Serviços Judiciários e Notariais",
                "Gestão Desportiva e de Lazer",
                "Gestão de Telecomunicações",
                "Gestão de Trânsito",
                "Gestão de Turismo",
                "Gestão Empresarial",
                "Gestão em Serviços",
                "Gestão Financeira",
                "Gestão Hospitalar",
                "Gestão Portuária",
                "Gestão Pública",
                "Gestão Tributária",
                "Horticultura",
                "Hotelaria",
                "Informática",
                "Planejamento Logístico de Cargas",
                "Podologia",
                "Polímeros",
                "Política e Gestão Cultural",
                "Políticas e Estratégicas Públicas",
                "Práticas Integrativas e Complementares",
                "Processamento de Dados",
                "Processos Ambientais",
                "Processos Escolares",
                "Processos Gerenciais",
                "Processos Metalúrgicos",
                "Processos Químicos",
                "Produção Agrícola",
                "Produção Agropecuária",
                "Produção Audiovisual",
                "Produção Cervejeira",
                "Produção Cultural",
                "Produção de Cacau e Chocolate",
                "Produção de Cachaça",
                "Produção de Fármacos",
                "Produção de Grãos",
                "Produção de Plástico",
                "Produção Fonográfica",
                "Produção Gráfica",
                "Produção Industrial",
                "Produção Leiteira",
                "Produção Multimídia",
                "Produção Musical",
                "Produção Pesqueira",
                "Produção Publicitária",
                "Produção Sucroalcooleira"
            ]
        }

        // Normalizar os nomes dos cursos e adicionar à tabela Course
        for (const [type, courseNames] of Object.entries(courseHigh)) {
            for (const name of courseNames) {
                const normalizedName = normalizeName(name);
                await prisma.course.create({
                    data: {
                        name: name,
                        normalizedName: normalizedName,
                        Type: type as AllEducationType
                    }
                });
                console.log(`Curso ${name} adicionado com sucesso!`);
            }
        }

        console.log("Todos os cursos foram adicionados com sucesso.");
    } catch (error) {
        console.error("Erro ao adicionar cursos:", error);
    } finally {
        await prisma.$disconnect();
    }
}

// Executar o script
addCourses();